version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - cs2-battle-bot-network

networks:
  cs2-battle-bot-network:
    external: true
