# Generated by Django 5.1.4 on 2025-05-08 19:19

import prefix_id.field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=26, prefix='map', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
