# Generated by Django 5.1.4 on 2025-05-10 23:38

import django.db.models.deletion
import prefix_id.field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0004_alter_guild_members_alter_guild_owner'),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='guild',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='guilds.guild'),
        ),
        migrations.CreateModel(
            name='MapPool',
            fields=[
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=31, prefix='map_pool', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('guild', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='map_pools', to='guilds.guild')),
                ('maps', models.ManyToManyField(related_name='map_pools', to='maps.map')),
            ],
        ),
    ]
