# Generated by Django 5.1.4 on 2025-05-11 18:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0004_alter_guild_members_alter_guild_owner'),
        ('maps', '0002_map_guild_mappool'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mappool',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='guild',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='guilds.guild'),
        ),
        migrations.AlterField(
            model_name='mappool',
            name='guild',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_pools', to='guilds.guild'),
        ),
    ]
