# Generated by Django 5.1.4 on 2024-12-15 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(related_name='guilds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
