# Generated by Django 5.1.4 on 2025-05-10 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0003_guild_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='guilds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guild',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_guilds', to=settings.AUTH_USER_MODEL),
        ),
    ]
