# Generated by Django 5.0.6 on 2024-07-07 16:38

import django.db.models.deletion
import prefix_id.field
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('embeds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=28, prefix='guild', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('guild_id', models.CharField(max_length=255)),
                ('lobby_channel', models.CharField(blank=True, max_length=255, null=True)),
                ('team1_channel', models.CharField(blank=True, max_length=255, null=True)),
                ('team2_channel', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='embeds.embed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
