# Generated by Django 5.0.6 on 2024-07-07 16:47

import django.db.models.deletion
import prefix_id.field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guilds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=29, prefix='server', primary_key=True, serialize=False, unique=True)),
                ('ip', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('port', models.PositiveIntegerField()),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('rcon_password', models.CharField(blank=True, max_length=100, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='guilds.guild')),
            ],
        ),
    ]
