# Generated by Django 5.0.2 on 2024-02-20 23:28

import django.db.models.deletion
import prefix_id.field
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordUser",
            fields=[
                (
                    "id",
                    prefix_id.field.PrefixIDField(
                        editable=False,
                        max_length=30,
                        prefix="dc_user",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SteamUser",
            fields=[
                (
                    "id",
                    prefix_id.field.PrefixIDField(
                        editable=False,
                        max_length=33,
                        prefix="steam_user",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("steamid64", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    prefix_id.field.PrefixIDField(
                        editable=False,
                        max_length=29,
                        prefix="player",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discord_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.discorduser",
                    ),
                ),
                (
                    "steam_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.steamuser",
                    ),
                ),
            ],
        ),
    ]
