# Generated by Django 5.0.2 on 2024-02-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="steamuser",
            name="avatar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="steamuser",
            name="profile_url",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="steamuser",
            name="steamid32",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="steamuser",
            name="steamid64",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
