# Generated by Django 5.0.2 on 2024-02-21 14:55

import django.db.models.deletion
import prefix_id.field
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0002_steamuser_avatar_steamuser_profile_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    prefix_id.field.PrefixIDField(
                        editable=False,
                        max_length=27,
                        prefix="team",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_leader",
                        to="players.player",
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(related_name="teams", to="players.player"),
                ),
            ],
        ),
    ]
