# Generated by Django 5.0.6 on 2024-05-10 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0005_alter_player_steam_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_leader",
                to="players.player",
            ),
        ),
    ]
