# Generated by Django 5.1.4 on 2025-05-08 19:19

import django.db.models.deletion
import prefix_id.field
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guilds', '0002_guild_created_at_guild_lobby_channel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=27, prefix='team', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_temp', models.BooleanField(default=True)),
                ('capitan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='capitan_team', to=settings.AUTH_USER_MODEL)),
                ('guild', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='guilds.guild')),
                ('players', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
