# Generated by Django 5.0.6 on 2024-07-13 18:35

import django.db.models.deletion
import prefix_id.field
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guilds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=27, prefix='team', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='guilds.guild')),
                ('players', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
