# Generated by Django 5.0.4 on 2024-04-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guilds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="lobby_channel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="guild",
            name="team1_channel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="guild",
            name="team2_channel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
