# Generated by Django 5.0.4 on 2024-04-21 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guilds", "0003_guild_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guild",
            name="members",
        ),
    ]
