# Generated by Django 5.0.6 on 2024-05-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guilds", "0005_embed_embedfield_guild_embed_embed_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="embedfield",
            name="order",
            field=models.IntegerField(default=1),
        ),
    ]
