# Generated by Django 5.0.2 on 2024-02-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0002_remove_match_map_remove_match_players_and_more"),
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="matches",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="servers", to="matches.match"
            ),
        ),
    ]
