# Generated by Django 5.0.4 on 2024-04-04 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guilds", "0002_guild_lobby_channel_guild_team1_channel_and_more"),
        ("servers", "0004_remove_server_matches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="guild",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servers",
                to="guilds.guild",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="rcon_password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
