# Generated by Django 5.1.4 on 2025-05-08 19:19

import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.fields
import matches.pydantic_schemas
import prefix_id.field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guilds', '0002_guild_created_at_guild_lobby_channel_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=34, prefix='matchconfig', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('game_mode', models.CharField(default='competitive', max_length=100)),
                ('type', models.CharField(choices=[('bo1', 'Bo1'), ('bo3', 'Bo3'), ('bo5', 'Bo5')], default='bo1', max_length=100)),
                ('map_sides', models.JSONField(default=dict)),
                ('players_per_team', models.IntegerField(default=5)),
                ('shuffle_teams', models.BooleanField(default=False)),
                ('clinch_series', models.BooleanField(default=False)),
                ('cvars', models.JSONField(default=dict)),
                ('guild', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='match_configs', to='guilds.guild')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('map_veto_started', 'Map Veto Started'), ('map_veto_ended', 'Map Veto Ended'), ('live', 'Live'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], default='created', max_length=100)),
                ('map_bans', django_pydantic_field.fields.PydanticSchemaField(config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=matches.pydantic_schemas.MapBan)),
                ('map_list', django_pydantic_field.fields.PydanticSchemaField(config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=matches.pydantic_schemas.MapList)),
                ('map_veto_state', models.JSONField(default=dict)),
                ('guild', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='guilds.guild')),
                ('team1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='teams.team')),
                ('team2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='teams.team')),
                ('config', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.matchconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
