# Generated by Django 5.1.4 on 2025-05-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchconfig',
            name='game_mode',
            field=models.CharField(choices=[('competitive', 'Competitive'), ('wingman', 'Wingman')], default='competitive', max_length=100),
        ),
    ]
