# Generated by Django 5.1.4 on 2025-05-10 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0004_alter_guild_members_alter_guild_owner'),
        ('matches', '0002_alter_matchconfig_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchconfig',
            name='guild',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_configs', to='guilds.guild'),
        ),
    ]
