# Generated by Django 5.1.4 on 2025-05-10 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_map_guild_mappool'),
        ('matches', '0003_alter_matchconfig_guild'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchconfig',
            name='map_pool',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_configs', to='maps.mappool'),
        ),
    ]
