# Generated by Django 5.1.4 on 2025-05-11 17:26

import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import matches.pydantic_schemas
import prefix_id.field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_matchconfig_map_pool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cvar',
            fields=[
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=27, prefix='cvar', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean')], default='boolean', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='matchconfig',
            name='cvars',
        ),
        migrations.AlterField(
            model_name='matchconfig',
            name='map_sides',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (matches.pydantic_schemas.SideChoice,))),
        ),
        migrations.AddField(
            model_name='matchconfig',
            name='cvars',
            field=models.ManyToManyField(blank=True, related_name='match_configs', to='matches.cvar'),
        ),
    ]
