# Generated by Django 5.1.4 on 2025-05-11 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0004_alter_guild_members_alter_guild_owner'),
        ('matches', '0005_cvar_remove_matchconfig_cvars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvar',
            name='guild',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvars', to='guilds.guild'),
        ),
    ]
