# Generated by Django 5.1.4 on 2025-05-11 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_cvar_guild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvar',
            name='value',
        ),
        migrations.AlterField(
            model_name='cvar',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cvar',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cvar',
            name='value_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean')], default='string', max_length=100),
        ),
        migrations.CreateModel(
            name='MatchConfigCvar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('cvar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.cvar')),
                ('match_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.matchconfig')),
            ],
            options={
                'unique_together': {('match_config', 'cvar')},
            },
        ),
        migrations.RemoveField(
            model_name='matchconfig',
            name='cvars',
        ),
        migrations.AddField(
            model_name='matchconfig',
            name='cvars',
            field=models.ManyToManyField(blank=True, related_name='match_configs', through='matches.MatchConfigCvar', to='matches.cvar'),
        ),
    ]
