# Generated by Django 5.1.4 on 2025-05-11 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_remove_cvar_value_alter_cvar_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='matchconfigcvar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchconfigcvar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
