services:
  app:
    image: qwizii/cs2-battle-bot-api:latest
    container_name: cs2_battle_bot_api_prod
    command: sh -c "gunicorn cs2_battle_bot.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"
    volumes:
      - static_volume:/app/staticfiles/
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - cs2-battle-bot-network
    tty: true
  db:
    image: postgres:15.1
    container_name: cs2_battle_bot_api_db_prod
    env_file:
        - .env
    restart: unless-stopped
    expose:
      - 5435
    healthcheck:
      test: "exit 0"
    networks:
      - cs2-battle-bot-network
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    container_name: cs2_battle_bot_api_redis_prod
    restart: unless-stopped
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - .env
    expose:
      - 6379
    networks:
      - cs2-battle-bot-network
  nginx:
    image: nginx:stable-alpine3.17-slim
    container_name: cs2_battle_bot_api_nginx_prod
    ports:
      - 8000:80
    volumes:
      - static_volume:/app/staticfiles/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - cs2-battle-bot-network
  bot:
    image: qwizii/cs2-battle-bot:latest
    container_name: cs2_battle_bot
    env_file:
      - .env
    networks:
      - cs2-battle-bot-network

networks:
  cs2-battle-bot-network:
    external: true

volumes:
  static_volume:
  pgdata: