# Generated by Django 5.0.2 on 2024-02-21 00:10

import django.db.models.deletion
import prefix_id.field
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("players", "0002_steamuser_avatar_steamuser_profile_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    prefix_id.field.PrefixIDField(
                        editable=False,
                        max_length=28,
                        prefix="match",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("status", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("map", models.CharField(max_length=255)),
                ("winner", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MatchPlayer",
            fields=[
                (
                    "id",
                    prefix_id.field.PrefixIDField(
                        editable=False,
                        max_length=35,
                        prefix="match_player",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "team",
                    models.CharField(
                        choices=[("CT", "CT"), ("T", "T")], default="CT", max_length=255
                    ),
                ),
                ("kills", models.IntegerField()),
                ("deaths", models.IntegerField()),
                ("assists", models.IntegerField()),
                ("headshots", models.IntegerField()),
                ("score", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="matches.match"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="players.player"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="players",
            field=models.ManyToManyField(
                through="matches.MatchPlayer", to="players.player"
            ),
        ),
    ]
