# Generated by Django 5.0.2 on 2024-03-01 12:33

import django.db.models.deletion
import prefix_id.field
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0002_remove_match_map_remove_match_players_and_more"),
        ("players", "0003_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    prefix_id.field.PrefixIDField(
                        editable=False,
                        max_length=26,
                        prefix="map",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("tag", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="matchteam",
            name="match",
        ),
        migrations.RemoveField(
            model_name="matchteam",
            name="team",
        ),
        migrations.RemoveField(
            model_name="match",
            name="teams",
        ),
        migrations.AddField(
            model_name="match",
            name="team1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_team1",
                to="players.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_team2",
                to="players.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="winner_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_winner",
                to="players.team",
            ),
        ),
        migrations.RemoveField(
            model_name="match",
            name="maps",
        ),
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("FINISHED", "Finished"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=255,
            ),
        ),
        migrations.DeleteModel(
            name="MatchPlayer",
        ),
        migrations.DeleteModel(
            name="MatchTeam",
        ),
        migrations.AddField(
            model_name="match",
            name="maps",
            field=models.ManyToManyField(related_name="matches_maps", to="matches.map"),
        ),
    ]
