# Generated by Django 5.0.2 on 2024-03-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0003_map_remove_matchteam_match_remove_matchteam_team_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
