# Generated by Django 5.0.2 on 2024-03-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0004_alter_match_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
