# Generated by Django 5.0.2 on 2024-03-03 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0006_alter_match_status_matchmapban_match_map_bans"),
        ("players", "0004_alter_team_leader"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchMapSelected",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="map_selected",
                        to="matches.map",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="map_selected",
                        to="players.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="map_selected",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_map_selected",
                to="matches.matchmapselected",
            ),
        ),
    ]
