# Generated by Django 5.0.2 on 2024-03-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0008_alter_match_map_selected"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="map_selected",
        ),
        migrations.AddField(
            model_name="match",
            name="map_picks",
            field=models.ManyToManyField(
                related_name="matches_map_picks", to="matches.matchmapselected"
            ),
        ),
    ]
