# Generated by Django 5.0.2 on 2024-03-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0009_remove_match_map_selected_match_map_picks"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="message_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
