# Generated by Django 5.0.2 on 2024-03-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0010_match_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="message_id",
            field=models.IntegerField(null=True),
        ),
    ]
