# Generated by Django 5.0.2 on 2024-03-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0011_alter_match_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="message_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
