# Generated by Django 5.0.2 on 2024-03-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0012_alter_match_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="author_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
