# Generated by Django 5.0.2 on 2024-03-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0013_match_author_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="clinch_series",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="cvars",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="map_sides",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="maplist",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="num_maps",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="match",
            name="players_per_team",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
