# Generated by Django 5.0.4 on 2024-04-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0014_match_clinch_series_match_cvars_match_map_sides_and_more"),
        ("players", "0004_alter_team_leader"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MatchMapBan",
            new_name="MapBan",
        ),
        migrations.RenameModel(
            old_name="MatchMapSelected",
            new_name="MapPick",
        ),
        migrations.AlterField(
            model_name="match",
            name="type",
            field=models.CharField(
                choices=[("BO1", "Bo1"), ("BO3", "Bo3"), ("BO5", "Bo5")],
                default="BO1",
                max_length=255,
            ),
        ),
    ]
