# Generated by Django 5.0.4 on 2024-04-04 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0016_match_server"),
        ("players", "0004_alter_team_leader"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="author_id",
        ),
        migrations.AddField(
            model_name="match",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="players.discorduser",
            ),
        ),
    ]
