# Generated by Django 5.0.4 on 2024-04-17 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guilds", "0003_guild_members"),
        ("matches", "0017_remove_match_author_id_match_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="guild",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="guilds.guild",
            ),
        ),
    ]
