# Generated by Django 5.0.6 on 2024-05-09 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0022_alter_map_guild_alter_mappool_guild_and_more"),
        ("players", "0005_alter_player_steam_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mappick",
            name="map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="map_picks",
                to="matches.map",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="players.discorduser",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="map_bans",
            field=models.ManyToManyField(
                blank=True, related_name="matches_map_bans", to="matches.mapban"
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="map_picks",
            field=models.ManyToManyField(
                blank=True, related_name="matches_map_picks", to="matches.mappick"
            ),
        ),
        migrations.AlterField(
            model_name="matchconfig",
            name="cvars",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="matchconfig",
            name="map_sides",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
