# Generated by Django 5.0.6 on 2024-05-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0024_remove_match_map_pool_matchconfig_map_pool"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchconfig",
            name="shuffle_teams",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("STARTED", "Started"),
                    ("LOADED", "Loaded"),
                    ("LIVE", "Live"),
                    ("FINISHED", "Finished"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="CREATED",
                max_length=255,
            ),
        ),
    ]
