# Generated by Django 5.0.6 on 2024-05-10 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guilds", "0005_embed_embedfield_guild_embed_embed_fields"),
        ("matches", "0025_matchconfig_shuffle_teams_alter_match_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="embed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="guilds.embed",
            ),
        ),
    ]
