# Generated by Django 5.0.6 on 2024-05-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0026_match_embed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("CAPTAINS_SELECT", "Captains Select"),
                    ("MAP_VETO", "Map Veto"),
                    ("READY_TO_LOAD", "Ready To Load"),
                    ("LOADED", "Loaded"),
                    ("LIVE", "Live"),
                    ("FINISHED", "Finished"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="CREATED",
                max_length=255,
            ),
        ),
    ]
