# Generated by Django 5.0.6 on 2024-05-10 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0027_alter_match_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="last_map_ban",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches_last_map_ban",
                to="matches.mapban",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="last_map_pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches_last_map_pick",
                to="matches.mappick",
            ),
        ),
    ]
