name: Publish Bot Docker Image

on:
    workflow_run:
        workflows: ["generate-schema.yml"]
        types:
            - completed

jobs:
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest

        steps:
            -   name: Check out the repo
                uses: actions/checkout@v4.1.1
            -   name: Check for changes
                id: check_changes
                run: |
                    if [[ $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}) == *"src"* ]]; then
                      echo "::set-output name=changes::true"
                    else
                      echo "::set-output name=changes::false"
                    fi

            -   name: Extract metadata (tags, labels) for Docker
                if: steps.check_changes.outputs.changes == 'true'
                id: meta
                uses: docker/metadata-action@v5.5.1
                with:
                    images: qwizii/cs2-battle-bot-test

            -   name: Log in to Docker Hub
                if: steps.check_changes.outputs.changes == 'true'
                uses: docker/login-action@v3.0.0
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Build and push Docker image
                uses: docker/build-push-action@v5.1.0
                if: steps.check_changes.outputs.changes == 'true'
                with:
                    context: ./src
                    file: ./src/Dockerfile
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
